import { createMuiTheme } from "@material-ui/core/styles";

const theme = createMuiTheme({
  background: "white",
  typography: {
    useNextVariants: true,

    button: {
      fontFamily: "Source Sans Pro",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "normal",
      textAlign: "justify",
      textTransform: "none",
      fontSize: "14px",
      fontWeight: 500,
      letterSpacing: "0.5px",
    },
    h1: {
      "font-family": "Source Sans Pro",
      "font-size": "32px",
      "font-weight": "bold",
      "font-stretch": "normal",
      "font-style": "normal",
      "line-height": "normal",
      "letter-spacing": "normal",
      textAlign: "center",
      color: "#2d3436",
    },
    h2: {
      "font-family": "Source Sans Pro",
      "font-size": "28px",
      "font-weight": "600",
      "font-stretch": "normal",
      "font-style": "normal",
      "line-height": "normal",
      "letter-spacing": "normal",
      color: "#2d3436",
    },
    h3: {
      "font-family": "Source Sans Pro",
      "font-size": "24px",
      "font-weight": "600",
      "font-stretch": "normal",
      "font-style": "normal",
      "line-height": "normal",
      "letter-spacing": "normal",
      color: "#2d3436",
    },
    h4: {
      "font-family": "Source Sans Pro",
      "font-size": "18px",
      "font-weight": "600",
      "font-stretch": "normal",
      "font-style": "normal",
      "line-height": "normal",
      "letter-spacing": "normal",
      color: "#2d3436",
    },
    subtitle1: {
      "font-family": "Source Sans Pro",
      "font-size": "28px",
      "font-weight": "bold",
      "font-stretch": "normal",
      "font-style": "normal",
      "line-height": "normal",
      "letter-spacing": "0.5px",
      color: "#2d3436",
    },
    subtitle2: {
      "font-family": "Source Sans Pro",
      "font-size": "16px",
      "font-weight": "600",
      "font-stretch": "normal",
      "font-style": "normal",
      "line-height": "normal",
      "letter-spacing": "0.5px",
      color: "#2d3436",
    },
    body1: {
      "font-family": "Source Sans Pro",
      "font-size": "16px",
      "font-weight": "normal",
      "font-stretch": "normal",
      "font-style": "normal",
      lineHeight: "normal",
      color: "#2d3436",
    },
    body2: {
      "font-family": "Source Sans Pro",
      "font-size": "16px",
      "font-weight": "normal",
      "font-stretch": "normal",
      "font-style": "normal",
      lineHeight: "normal",
      // textAlign: "center",
      color: "#636e72",
    },
    content: {
      fontFamily: "Source Sans Pro",
      fontSize: "18px",
      fontWeight: "normal",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "1px",
      textAlign: "justify",
    },

    caption: {
      "font-family": "Source Sans Pro",
      "font-size": "11px",
      "font-weight": "600",
      "font-stretch": "normal",
      "font-style": "normal",
      lineHeight: "normal",
      "letter-spacing": "normal",
      "text-align": "justify",
      color: "#636e72",
    },
  },
  palette: {
    primary: {
      main: "#fd5c3e",
    },
    secondary: {
      main: "#FFFFFF",
    },
    background: {
      main: "#FFFFFF",
    },
    error: { main: "#CC2C1C" },
    warning: { main: "#FC642D" },
    info: { main: "#08549E" },
    text: { main: "#FC642D" },
    icon: { main: "#757575" },
  },
  shape: {
    borderRadius: 5,
  },
  overrides: {},
});

export default theme;
