export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_ERROR = "UPDATE_ERROR";
export const SET_LOADING = "SET_LOADING";

// Messenger contacts
export const FETCH_MESSENGER_CONTACT_LIST = "FETCH_MESSENGER_CONTACT_LIST";
export const MESSENGER_CONTACT_IS_LOADING = "MESSENGER_CONTACT_IS_LOADING";
export const MESSENGER_CONTACT_ERROR = "MESSENGER_CONTACT_ERROR";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const ADD_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
// Messenger contacts

// Messenger messages
export const MESSENGER_MESSAGE_IS_LOADING = "MESSENGER_MESSAGE_IS_LOADING";
export const FETCH_MESSENGER_MESSAGE_LIST = "FETCH_MESSENGER_MESSAGE_LIST";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const MESSENGER_MESSAGES_ERROR = "MESSENGER_MESSAGES_ERROR";
// Messenger messages
